<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

abstract class BaseController extends AbstractController
{
    protected string $title = "";

    protected function render(string $view, array $parameters = [], ?Response $response = null): Response
    {
        $parameters['title'] = $this->title;
        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }
}
