<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

abstract class BaseController extends AbstractController
{
    protected string $title = "";

    /**
     * @param string $view
     * @param array $parameters
     * @param Response|null $response
     *
     * @return Response
     */
    protected function render(string $view, array $parameters = [], ?Response $response = null): Response
    {
        $parameters['title'] = $this->title;
        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @param int $status
     * @param array $headers
     *
     * @return Response
     */
    protected function jsonResponse(array $data, int $status = Response::HTTP_OK, array $headers = ['Content-Type' => 'application/json']): Response{
        return new Response(json_encode($data), $status, $headers);
    }
}
